const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
const ROLE_BUSINESS_OWNER = 'BUSINESS_OWNER';
const ROLE_BUSINESS_TELLER = 'BUSINESS_TELLER';
const ROLE_CUSTOMER = 'CUSTOMER';

module.exports = {
  ROLE_SUPER_ADMIN,
  ROLE_BUSINESS_OWNER,
  ROLE_BUSINESS_TELLER,
  ROLE_CUSTOMER
}